### PR TITLE
2015-10-14 00:24 UTC+0200 Viktor Szakats (vszakats users.noreply.gith…

### PR DESCRIPTION
**Pull request by omm**
Another attempt of Pull Request. Viktor, now it's a right way?

### CODE REVIEW

**Comment by vszakats** [comment]
Thank you Alexey, it looks perfect!

**Comment by omm** [comment]
Ok, thank you, and what a next step to push changes to harbour/core?

**Comment by vszakats** [comment]
You (or another dev around) can press the green "Merge pull request" button on this page to get it merged.

**Comment by omm** [comment]
ok, done.

**Comment by vszakats** [comment]
👍🏻

**Pull request merged**
