### PR TITLE
2015-10-28 14:23 UTC+0200 Alexey Myronenko (m.oleksa ukr.net)

### PR DESCRIPTION
**Pull request by omm**
Hi!

Can ayone review last changes and compare sample behavior with clipper, thanks.

### CODE REVIEW

**Comment by vszakats** [comment]
Hi @omm, see my sightly updated version at https://github.com/vszakats/harbour-core/commit/a4bf115f79e2f24685cbc4ffbe97caba4165a767, after verifying it against Cl*pper.

**Comment by omm** [comment]
Ok, Your version better than mine.
 I'll close my PR and if you don't mind i'll push your version as i did last time.

**Comment by vszakats** [comment]
Of course, please do!

**Comment by omm** [comment]
Done.

**Pull request closed without merging**
