### PR TITLE
functions: Harbour socket API - HB_SOCKETSETNOSIGPIPE

### PR DESCRIPTION
**Pull request by lailton**
2023-01-17 13:10 UTC-0300 Lailton Fernando Mariano (lailton/at/paysoft.com.br)
  * include/hbsocket.h
  * src/harbour.def
  * src/rtl/hbsocket.c
  * src/rtl/hbsockhb.c
    + added functions: Harbour socket API
      HB_SOCKETSETNOSIGPIPE( hSocket, lValue ) --> lSuccess

### CODE REVIEW

**Comment by alcz** [comment]
May I ask on which platform you need this? macOS?
Surely on Linux there are direct flags passed during socket operations, 
that any socket fault won't generate a signal.

Lailton wrote:

**Comment by lailton** [comment]
Hi @alcz 
I use it for Android/iOS and MacOS application when I make websocket server.
It is too supported by Linux.

**Comment by alcz** [comment]
https://github.com/harbour/core/blob/master/src/rtl/hbsocket.c#L2636-L2654
You should not need it if you don't use low level socket functions directly.
What i really mean, if MacOS/Darwin does not know what MSG_NOSIGNAL is... then as a solution we really need to set it by default for that platform. So that HB_SOCKETSETNOSIGPIPE() is set by default on all sockets by default. Average Harbour app is not ready to process signals.

**Comment by lailton** [comment]
I have no idea what is "MSG_NOSIGNAL", I dont see it defined anywhere harbour source. so it means that block code will not be executed at all. or Am I wrong? I will search better.

**Comment by lailton** [comment]
@alcz 
Look at this between line 44 and 67
https://android.googlesource.com/platform/external/parameter-framework/+/refs/tags/android-n-preview-1/remote-processor/Socket.cpp

**Comment by alcz** [comment]
Yes, i think it would be nice to have similar setup, so that a basic Harbour socket usage is correct on Mac without bothering with signals in .prg code. 

```diff
--- a/src/rtl/hbsocket.c
+++ b/src/rtl/hbsocket.c
@@ -2555,6 +2555,11 @@ HB_SOCKET hb_socketAccept( HB_SOCKET sd, void ** pSockAddr, unsigned * puiLen, H
           * explicitly.
           */
          hb_socketSetBlockingIO( newsd, HB_TRUE );
+#if ( defined( HB_OS_UNIX ) && ! defined( MSG_NOSIGNAL ) && \
+   defined( SO_NOSIGPIPE ) )
+         /* prevent SIGPIPE on OS without MSG_NOSIGNAL (Darwin, macOS) */
+         hb_socketSetNoSigPipe( newsd, HB_TRUE );
+#endif
       }
 
       hb_socketSetOsError( err );
@@ -2586,6 +2591,11 @@ int hb_socketConnect( HB_SOCKET sd, const void * pSockAddr, unsigned uiLen, HB_M
       ret = hb_socketSelectWRE( sd, timeout );
       if( ret > 0 )
       {
+#if ( defined( HB_OS_UNIX ) && ! defined( MSG_NOSIGNAL ) && \
+   defined( SO_NOSIGPIPE ) )
+         /* prevent SIGPIPE on OS without MSG_NOSIGNAL (Darwin, macOS) */
+         hb_socketSetNoSigPipe( sd, HB_TRUE );
+#endif
          hb_socketSetError( 0 );
          ret = 0;
       }
```

**Comment by lailton** [comment]
@alcz
Yes, It looks fine.
maybe you can create a new PR and we can hava some time to test it.

**Pull request merged**
