### PR TITLE
2015-10-23 10:33 UTC+0200 Alexey Myronenko (m.oleksa/at/ukr.net)

### PR DESCRIPTION
**Pull request by omm**

### CODE REVIEW

**Comment by vszakats** [comment]
When pulling a patch from another branch/fork, it'd probably be best pulling it as-is, instead of relabelling under another author name, timestamp and stripping original references. Referring to this original commit with my original changelog text identical to this PR: https://github.com/vszakats/harbour-core/commit/53a8151b99543ded196675fb8481021db5bdf423

**Comment by omm** [comment]
Viktor, sorry. Pull request closed. What about to merge from your fork to harbour/core?

**Comment by vszakats** [comment]
Hi Alexey, probably a PR is not the easiest way in this case, but you can take the full original diff using this URL: https://github.com/vszakats/harbour-core/commit/53a8151b99543ded196675fb8481021db5bdf423.diff

apply that and create PR for it.

(or the full patch using this URL:
https://github.com/vszakats/harbour-core/commit/53a8151b99543ded196675fb8481021db5bdf423.patch)

**Comment by omm** [comment]
Trying apply the diff or patch i get the next
D:\dev_d\_git\omm\core>git apply ..\53a8151b99543ded196675fb8481021db5bdf423.diff
error: patch failed: ChangeLog.txt:5
error: ChangeLog.txt: patch does not apply
error: patch failed: src/rtl/achoice.prg:283
error: src/rtl/achoice.prg: patch does not apply

What is wrong?

**Comment by vszakats** [comment]
I had only every tried with the `patch` command (`patch -p1 -i <fn>` or similar) yet. It should work, though it is possible a patch needs manual interaction if some hunks fail to apply automatically (ChangeLog.txt is typically such file in its mainline version - it's better in my fork). Get `patch` from <https://git-for-windows.github.io/>

[ There are many ways to apply patches with various pros and cons, maybe there is even something easier or better than I suggest, it's worth googling for it. Above suits this case well enough though. ]

**Comment by vszakats** [comment]
BTW, on a second look probably for `git apply` you'd need the `.patch` format. I'm not sure.

**Comment by omm** [comment]
I tried .diff and .patch, the result is identical in both cases. Ok, will dig on.

**Pull request closed without merging**
