### PR TITLE
2021-01-18 20:44 UTC+0200 Oleksii Myronenko (m.oleksa ukr.net)

### PR DESCRIPTION
**Pull request by omm**
Sorry, this is a new pull request, with one commit, instead of https://github.com/harbour/core/pull/224

### CODE REVIEW

**Comment by tuffnatty** [comment]
I would keep the empty array/hash check where it is, just add some more.
Here is a sample .prg which I can reliably use to crash the debugger:
```xbase
function main()
local a:={{},{{}},{=>},{1=>{=>}},{{=>}}}
altd()
?"qqq"
```

**Comment by omm** [comment]
New commits, to check if an array/hash is empty, are moved to (KP_ENTER handler) as suggested by @tuffnatty (thanks), to avoid a situation where move from an array to empty array, or hash to empty hash, due to the call of the AddWindows() method, without checks on len(array/hash) == 0.

**Comment by tuffnatty** [comment]
Looks fine! Can you please rebase the branch against current HEAD, there's a conflict in ChangeLog.txt?

**Comment by tuffnatty** [comment]
Merged manually.

**Comment by omm** [comment]
Thanks a lot.

**Pull request closed without merging**
