### PR TITLE
Added new curl 64-bit libraries name

### PR DESCRIPTION
**Pull request by EMG60**
Added new curl 64-bit libraries name

### CODE REVIEW

**Comment by EMG60** [comment]
Why so much time for such a simple fix? Please commit!

**Comment by tuffnatty** [comment]
Please re-read your commit. You've put the file in a wrong path. Please consider committing complete changes - is curl working well for you after the change? Did not curl have any API changes in these years?

**Comment by EMG60** [comment]
Ok, understood. I give up.

**Comment by EMG60** [comment]
Ok, one more try. Can it be commited now, please?

**Comment by EMG60** [comment]
I already have full access to xHarbour and FWH repositories, and used to be full access to this repository in the past. I ask to have full access to this repository now, please. I can't work properly this way, as I already work for the other projects. What is the official way to ask for full access to this repository?

**Comment by EMG60** [comment]
Can I know why my pull request is not committed yet, please?

**Comment by tuffnatty** [comment]
Hi Enrico,
on the matter of your pull request: after a couple of weeks of reading hbcurl code and Viktor's updates, I think that your proposed change is basically safe and correct but not sufficient to make hbcurl work again (on most platforms). I am preparing a hbcurl update now which will include this and other fixes by Viktor.

**Pull request closed without merging**
