### PR TITLE
 Added HB_CURLOPT_DEBUGBLOCK in hbcurl

### PR DESCRIPTION
**Pull request by APerricone**

### CODE REVIEW

**Review by lailton — APPROVED** [review]
LGTM, why it was not merged yet?

**Comment by APerricone** [comment]
there is a conflict on ChangeLog.txt, @lailton can you resolve it or I must do it?

**Comment by APerricone** [comment]
the "force push" deleted my changes

**Comment by lailton** [comment]
@APerricone, I will take look and rebase your changes and open a new PR with the codes, thanks

**Pull request closed without merging**
